/**
 * Author: Professor Krasso
 * Date: 7 August 2024
 * File: app.js
 * Description: Application setup. Autogenerated using Express generator.
 */
'use strict';

// require statements
const express = require('express');
const mongoose = require('mongoose');
const cookieParser = require('cookie-parser');
const logger = require('morgan');
const { notFoundHandler, errorHandler } = require('./routes/utils/error-handler');
const connectToDatabase = require('./routes/utils/mongoose'); // Import Connection



// Importing the index router
const indexRouter = require('./routes/index');

// Importing the dashboard router
const dashboardRouter = require('./routes/dashboard');

// Importing User Management router
const usersRouter = require('./routes/users');
const securityRouter = require("./routes/security");

// Importing the inventory router
const viewInventoryRouter = require('./routes/inventory/view-inventory-items');
const createInventoryRouter = require('./routes/inventory/create-inventory-item');
const deleteInventoryRouter = require('./routes/inventory/delete-inventory-item');
const updateInventoryRouter = require('./routes/inventory/update-inventory-item');

// Importing the supplier router
const viewSupplierRouter = require('./routes/supplier/view-suppliers');
const createSupplierRouter = require('./routes/supplier/create-supplier');
const deleteSupplierRouter = require('./routes/supplier/delete-supplier');
const updateSupplierRouter = require('./routes/supplier/update-supplier');

// Importing the category router
const viewCategoryRouter = require('./routes/categories/view-categories');
const createCategoryRouter = require('./routes/categories/create-category');
const deleteCategoryRouter = require('./routes/categories/delete-category');
const updateCategoryRouter = require('./routes/categories/update-category');

// Importing search router
const searchRouter = require('./routes/search')

// Connect to MongoDB using Mongoose
connectToDatabase();  // Initializes DB Connection

// Variable declaration for the express app
const app = express();

// CORS configuration
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*'); // This allows all origins
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS'); // Allowed request methods
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept'); // Allowed headers
  next();
});

// Express app configuration Middleware
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Routing configuration
app.use('/api', indexRouter);
app.use('/api/dashboard', dashboardRouter);

// User Routes
app.use('/api/users', usersRouter);
app.use('/api/security', securityRouter);

// Inventory Routes
app.use('/api/reports/inventory/view', viewInventoryRouter);
app.use('/api/reports/inventory/create', createInventoryRouter);
app.use('/api/reports/inventory/delete', deleteInventoryRouter);
app.use('/api/reports/inventory/update', updateInventoryRouter);

// Supplier Routes
app.use('/api/reports/suppliers/view', viewSupplierRouter);
app.use('/api/reports/suppliers/create', createSupplierRouter);
app.use('/api/reports/suppliers/delete', deleteSupplierRouter);
app.use('/api/reports/suppliers/update', updateSupplierRouter);

// Category Routes
app.use('/api/reports/categories/view', viewCategoryRouter);
app.use('/api/reports/categories/create', createCategoryRouter);
app.use('/api/reports/categories/delete', deleteCategoryRouter);
app.use('/api/reports/categories/update', updateCategoryRouter);

// Search Routes
app.use('/api/search', searchRouter);

// Use the error handling middleware
app.use(notFoundHandler);
app.use(errorHandler);

// Export the app
module.exports = app;
